# -*- coding: utf-8 -*-
"""Hack_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbKuSEbNMX-S84TAvqZXFt4h-a4Emv4f
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

df = pd.read_csv('PS25_Dataset_25.csv/PS25_Dataset_25.csv')

pd.set_option('display.max_rows', None)
print("Dataset Preview:\n")
print(df.head())
print(df.tail())

print(df.isnull().sum())
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

df[['A','B','C','D']].mean()

plt.figure()

df[['A','B','C','D']].mean().plot(kind='bar'  , edgecolor = "black")

plt.title("Average Comparison of A, B, C, D")
plt.xlabel("Columns")
plt.ylabel("Average Values")
plt.xticks(rotation=0)

plt.show()

df['Total'] = df['A'] + df['B'] + df['C'] + df['D']
df['Average'] = df['Total'] / 4

plt.figure()

plt.hist(df['Average'], bins=10 , edgecolor = "black")

plt.title("Distribution of Average Values")
plt.xlabel("Average")
plt.ylabel("Frequency")

plt.show()

values = df[['A','B','C','D']].sum()

plt.figure()
plt.pie(values, labels=['A','B','C','D'], autopct='%1.1f%%' )

plt.title("Contribution of A, B, C, D")
plt.show()

df['Consistency'] = df[['A','B','C','D']].std(axis=1)

plt.hist(df['Consistency'], bins=10 , color ='cyan' , edgecolor = "black")
plt.title("Consistency Distribution")
plt.xlabel("Standard Deviation")
plt.ylabel("Frequency")
plt.show()